### ISSUE TITLE
fatal error: concurrent map writes

### ISSUE THREAD

**Issue by ringsaturn** [vearne/gin-timeout#10]
有遇到过这个 `concurrent map writes` 报错吗？

我在生产环境使用了这个中间件，然后时不时会发生这个报错，无法被 recover 机制兜底保护住，服务直接挂了

```
fatal error: concurrent map writes

goroutine 114163 [running]:
runtime.throw(0xe31401, 0x15)
#011/usr/local/go/src/runtime/panic.go:1117 +0x72 fp=0xc00da91b80 sp=0xc00da91b50 pc=0x43da52
runtime.mapassign_faststr(0xdd62e0, 0xc013ccf920, 0xe29979, 0xc, 0x6eac460)
#011/usr/local/go/src/runtime/map_faststr.go:211 +0x3f1 fp=0xc00da91be8 sp=0xc00da91b80 pc=0x419ef1
github.com/gin-gonic/gin/render.writeContentType(0x7f38203efc10, 0xc0224907e0, 0x1451d60, 0x1, 0x1)
#011/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/render/render.go:38 +0xaa fp=0xc00da91c28 sp=0xc00da91be8 pc=0x9efaca
github.com/gin-gonic/gin/render.WriteJSON(0x7f38203efc10, 0xc0224907e0, 0xcb5400, 0xc013c44120, 0xc022490800, 0x7f38203efc10)
#011/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/render/json.go:68 +0x5d fp=0xc00da91c70 sp=0xc00da91c28 pc=0x9ee23d
github.com/gin-gonic/gin/render.JSON.Render(...)
#011/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/render/json.go:55
github.com/gin-gonic/gin/render.(*JSON).Render(0xc011db0120, 0x7f38203efc10, 0xc0224907e0, 0x7f38203efc10, 0xc0224907e0)
#011<autogenerated>:1 +0x65 fp=0xc00da91cb0 sp=0xc00da91c70 pc=0x9f0d85
github.com/gin-gonic/gin.(*Context).Render(0xc0000c4500, 0x194, 0xfd2b18, 0xc011db0120)
#011/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/context.go:913 +0x149 fp=0xc00da91cf0 sp=0xc00da91cb0 pc=0x9f7429
github.com/gin-gonic/gin.(*Context).JSON(...)
#011/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/context.go:956
[XXXXXXXXX]
[XXXXXXXXX]
[XXXXXXXXX]
[XXXXXXXXX]
github.com/gin-gonic/gin.(*Context).Next(...)
#011/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/context.go:165
[XXXXXXXXX]
[XXXXXXXXX]
github.com/gin-gonic/gin.(*Context).Next(...)
#011/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/context.go:165
github.com/vearne/gin-timeout.Timeout.func1.1(0xc0224908a0, 0xc0000c4500, 0xc00d90a780)
#011/go/pkg/mod/github.com/vearne/gin-timeout@v0.0.6/timeout.go:58 +0x68 fp=0xc00da91fc8 sp=0xc00da91f90 pc=0xc513e8
runtime.goexit()
#011/usr/local/go/src/runtime/asm_amd64.s:1371 +0x1 fp=0xc00da91fd0 sp=0xc00da91fc8 pc=0x477c21
created by github.com/vearne/gin-timeout.Timeout.func1
#011/go/pkg/mod/github.com/vearne/gin-timeout@v0.0.6/timeout.go:52 +0x34a
```

配置如下

```go
	router.Use(
		timeout.Timeout(
			timeout.WithTimeout(150*time.Millisecond),                             // 这个指标需要调整
			timeout.WithErrorHttpCode(http.StatusRequestTimeout),                  // 可选参数
			timeout.WithDefaultMsg("{\"status\":\"failed\",\"msg\":\"timeout\"}"), // 可选参数
			timeout.WithCallBack(func(r *http.Request) {
				fmt.Println("timeout happen, url:", r.URL.String())
			},
			),
		),
	)
```

**Comment by vearne** [comment]
https://github.com/vearne/gin-timeout/blob/master/example/panic.go

**Comment by vearne** [comment]
另外golang里面，每个协程必须单独recover，任何一个协程崩溃，整个程序都会崩溃。

**Comment by ringsaturn** [comment]
内部检查的时候发现其他的 middleware 在尝试往已经关闭的 broken pipe 写数据，引起了连锁反应，不是单纯的 timeout 中间件导致的问题
